* Facebook (Politicl)

  [https://developers.facebook.com/apps/185174771986249/dashboard/]

  [https://developers.facebook.com/docs/javascript/quickstart]

  [https://developers.facebook.com/docs/javascript/reference/FB.init/v2.9]

Politicl
This app is public and available to all users
API Version
v2.8
App ID
185174771986249
App Secret
432c2ff03f4ab82eb332c48f67b89fc5



* Twitter (Politicl Login)

  [https://apps.twitter.com/app/12836738/keys]

  [https://dev.twitter.com/web/sign-in/implementing]

** Application Settings

Keep the "Consumer Secret" a secret. This key should never be human-readable in your application.
Consumer Key (API Key)	rkBigq6to0XYLpn81HwfkvweJ
Consumer Secret (API Secret)	30D0x2SOCHaU5bzyRWPfw8DCRleOFVyIRmQjRBfzvk4QV2xz6N
Access Level	Read and write (modify app permissions)
Can request a user's email address
Owner	GetPoliticl
Owner ID	2940065714


** Your Access Token

This access token can be used to make API requests on your own account's behalf. Do not share your access token secret with anyone.
Access Token	2940065714-kE1sBFQj1KCG7TI7UzBGTwgDsTR7JwOM8alLVH3
Access Token Secret	cnqD4ubhilKScTQwjtW1fflUTl1UbUAjMG2QIfCqbhKGv
Access Level	Read and write
Owner	GetPoliticl
Owner ID	2940065714


